using UnityEngine;

public class ProceduralAudioManager : MonoBehaviour
{
    [System.Serializable]
    public class SoundProfile
    {
        [Header("Duración y Volumen")]
        [Range(0.01f, 2f)] public float duration = 0.15f;
        [Range(0f, 1f)] public float volume = 0.2f;

        [Header("Síntesis Aditiva")]
        [Range(10, 150)] public int numberOfOscillators = 80;
        [Range(20f, 20000f)] public float minFrequency = 100f;
        [Range(20f, 20000f)] public float maxFrequency = 12000f;

        [Header("Suavizado (Fade In/Out)")]
        [Range(0.001f, 0.05f)] public float fadeTime = 0.005f;
    }

    [Header("--- PERFILES DE SONIDO PERSONALIZABLES ---")]
    public SoundProfile soundHoverProfile = new SoundProfile
    {
        duration = 0.04f,
        volume = 0.15f,
        numberOfOscillators = 40,
        minFrequency = 3000f,
        maxFrequency = 9000f
    };

    public SoundProfile soundOnProfile = new SoundProfile
    {
        duration = 0.12f,
        volume = 0.25f,
        numberOfOscillators = 80,
        minFrequency = 800f,
        maxFrequency = 6000f
    };

    public SoundProfile soundOffProfile = new SoundProfile
    {
        duration = 0.15f,
        volume = 0.20f,
        numberOfOscillators = 80,
        minFrequency = 100f,
        maxFrequency = 1200f
    };

    [Header("Referencias (Autogenerated)")]
    public AudioSource commonAudioSource;
    public AudioClip soundON;
    public AudioClip soundOFF;
   

    private void Awake()
    {
        GenerateAllSounds();
    }

    // Permite regenerar los audios desde el menú contextual del Inspector
    [ContextMenu("Regenerar Audios")]
    public void GenerateAllSounds()
    {
        if (commonAudioSource == null)
        {
            commonAudioSource = GetComponent<AudioSource>();
        }

       
        soundON = CreateAdditiveNoiseClip("Generated_SoundON", soundOnProfile);
        soundOFF = CreateAdditiveNoiseClip("Generated_SoundOFF", soundOffProfile);

        RadioController radio = GetComponent<RadioController>();
        if (radio != null)
        {
            radio.soundON = soundON;
            radio.soundOFF = soundOFF;
        
        }
    }

    private AudioClip CreateAdditiveNoiseClip(string clipName, SoundProfile profile)
    {
        int sampleRate = AudioSettings.outputSampleRate;
        int totalSamples = Mathf.CeilToInt(sampleRate * profile.duration);
        float[] sampleBuffer = new float[totalSamples];
        System.Random systemRandom = new System.Random();

        float[] phases = new float[profile.numberOfOscillators];
        for (int i = 0; i < profile.numberOfOscillators; i++)
        {
            phases[i] = (float)(systemRandom.NextDouble() * 2.0 * Mathf.PI);
        }

        int fadeSamples = Mathf.Min(Mathf.CeilToInt(sampleRate * profile.fadeTime), totalSamples / 2);

        for (int i = 0; i < totalSamples; i++)
        {
            float sampleValue = 0f;

            for (int j = 0; j < profile.numberOfOscillators; j++)
            {
                float randomVal = (float)systemRandom.NextDouble();
                float dynamicFrequency = profile.minFrequency + (randomVal * (profile.maxFrequency - profile.minFrequency));

                sampleValue += Mathf.Sin(phases[j]);

                phases[j] += 2f * Mathf.PI * dynamicFrequency / sampleRate;
                if (phases[j] > 2f * Mathf.PI)
                {
                    phases[j] -= 2f * Mathf.PI;
                }
            }

            sampleValue = (sampleValue / profile.numberOfOscillators) * profile.volume;

            // Envolvente Fade In / Fade Out
            float fadeEnvelope = 1f;
            if (i < fadeSamples && fadeSamples > 0)
            {
                fadeEnvelope = (float)i / fadeSamples;
            }
            else if (i > totalSamples - fadeSamples && fadeSamples > 0)
            {
                fadeEnvelope = (float)(totalSamples - i) / fadeSamples;
            }

            sampleBuffer[i] = sampleValue * fadeEnvelope;
        }

        AudioClip generatedClip = AudioClip.Create(clipName, totalSamples, 1, sampleRate, false);
        generatedClip.SetData(sampleBuffer, 0);

        return generatedClip;
    }
}